name: change management

on:
  pull_request_review:
    types: [submitted, edited, dismissed]
  workflow_call:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ $default-branch ]
  


permissions:
  pull-requests: write
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
